### PR TITLE
Image link update

### LINKED ISSUE #25: Many broken image links
Many broken icon images links from the wiki started to appear recently. From a quick diagnosis, it looks like the majority can be fixed by switching the default space replacement character from dash ('-') to underscore ('_') for icons.

### PR DESCRIPTION
**Pull request by NixonK**
Fixes #25

### CODE REVIEW

**Comment by NixonK** [comment]
Changed to WIP.
Fixing the variable names to shorten the special_icons list

**Comment by NixonK** [comment]
Removed from WIP.
- variable names now match in-game item names - which are also now the standard used by the wiki.

**Comment by mpsijm** [comment]
Thanks @NixonK for this pull request :tada: 
I hope this can be merged soon, then I can normally use the planner again :smile:

**Comment by doomeer** [comment]
Very nice patch, thanks a lot!

**Comment by doomeer** [comment]
I changed Char.lowercase_ascii to Char.lowercase. lowercase_ascii is better because lowercase is deprecated, but on the other hand, lowercase_ascii is only available in OCaml 4.03.

**Pull request merged**
