### PR TITLE
Recipies for 0.17

### PR DESCRIPTION
**Pull request by SamuelWr**
Originally Lava84flow's PR, with minimal changes to make it compile

### CODE REVIEW

**Comment by Lava84flow** [comment]
Dur, didn't even see those other bits... I also don't really know OCaml, so..

**Comment by keeshoekzema** [comment]
You missed the Low Density Structure change in this PR, should be:
    [ 2., steel_plate; 20., copper_plate; 5., plastic_bar ]
(https://wiki.factorio.com/index.php?title=Low_density_structure)

**Comment by Lava84flow** [comment]
dur... I didn't think that the low density stuff got changed

**Comment by SamuelWr** [comment]
@Lava84flow I wouldn't have seen it either without compiling it. As it was I spent 30 minutes getting the right compiler version and packages, and only about 10 fixing the compile errors

@keeshoekzema Thank you, I'll fix that

**Comment by YenzRanger** [comment]
Do you mind to commit the `factorio.js` as well. The readme states

> `factorio.js` is the Javascript compiled from the OCaml code. It is included in the repository in case you don't want to compile it.

That would help me (and probably others) at lot.

**Comment by doomeer** [comment]
Hey, thanks a lot for your efforts! I see that I'll try to merge and publish this as soon as possible.

Don't worry about factorio.js, I always re-generate it anyway (otherwise one could commit a malicious one).

**Pull request merged**
