### PR TITLE
Better css for small screen or windows

### PR DESCRIPTION
**Pull request by TheOddler**
When a windows is too small the right column gets all squished, and hard to read. This updates the css to solve it. It simply removes the column layout when the screen gets too small.

I chose 72em as the minimum width required for the column layout. Anything smaller makes the right column look squished I think.

To test, simply open the app and make your browser window very thin.

### CODE REVIEW

**Comment by doomeer** [comment]
Thanks a lot! Sorry I did not see your PR sooner. I'll test it asap :)

**Comment by TheOddler** [comment]
No problem! Hopefully you like it.

**Comment by doomeer** [comment]
Just tested, this is awesome :) I'll upload it to my website.

**Comment by TheOddler** [comment]
Awesome! It's a simple change, but it does the trick very nicely I though. Glad you agree :D

**Pull request merged**
